/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CUP.Parser;
import JFlex.SymbolTable;
import JFlex.LexerScanner;
import JFlex.SymbolTable;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ScannerBuffer;
import java_cup.runtime.XMLElement;

/**
 *
 * @author Mohamad Amin Javan
 */
public class ResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionsJPanel
     */
    public ResultJPanel() {
        CreateResult();
        initComponents();
        TLjTextPane.setText(Main.Data.TLOutput);
        TLjTextPane.setEnabled(false);
        PTjTextPane.setText(Main.Data.PTOutput);
        PTjTextPane.setEnabled(false);
        ParsejTextPane.setText(Main.Data.ParseOutput);
        ParsejTextPane.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrameTitlejLabel = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        TLjScrollPane = new javax.swing.JScrollPane();
        TLjTextPane = new javax.swing.JTextPane();
        PTjScrollPane = new javax.swing.JScrollPane();
        PTjTextPane = new javax.swing.JTextPane();
        ParsejScrollPane = new javax.swing.JScrollPane();
        ParsejTextPane = new javax.swing.JTextPane();
        ReturnjButton = new javax.swing.JButton();

        MainFrameTitlejLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        MainFrameTitlejLabel.setText("Java Compiler Project");
        MainFrameTitlejLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TLjTextPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TLjScrollPane.setViewportView(TLjTextPane);

        jTabbedPane.addTab("Tokens List", TLjScrollPane);

        PTjTextPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        PTjScrollPane.setViewportView(PTjTextPane);

        jTabbedPane.addTab("Parse Table", PTjScrollPane);

        ParsejScrollPane.setViewportView(ParsejTextPane);

        jTabbedPane.addTab("Parse", ParsejScrollPane);

        ReturnjButton.setText("Return");
        ReturnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainFrameTitlejLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnjButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainFrameTitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturnjButton)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnjButtonActionPerformed

        Main.Data.MF.setContentPane(Main.Data.MF.cp);
        Main.Data.MF.pack();

    }//GEN-LAST:event_ReturnjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainFrameTitlejLabel;
    private javax.swing.JScrollPane PTjScrollPane;
    private javax.swing.JTextPane PTjTextPane;
    private javax.swing.JScrollPane ParsejScrollPane;
    private javax.swing.JTextPane ParsejTextPane;
    private javax.swing.JButton ReturnjButton;
    private javax.swing.JScrollPane TLjScrollPane;
    private javax.swing.JTextPane TLjTextPane;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables

    private void CreateResult() {

        ComplexSymbolFactory csf = new ComplexSymbolFactory();
        SymbolTable iden = null;
        ScannerBuffer lexer = new ScannerBuffer(iden);
        XMLElement e = null;
        Parser p = null;
        try {
            iden = new SymbolTable(new BufferedReader(new FileReader(Main.Data.file.getAbsolutePath())), csf);
            p = new Parser(lexer, csf);
            e = (XMLElement) p.parse().value;
        } catch (Exception ex) {
            Logger.getLogger(ResultJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String parse_debug = getDebug_parser(p);
        
        Main.Data.ST = ST;
        Main.Data.PTOutput = ST.CreateTable();

        
        ScannerBuffer lexer = new ScannerBuffer(ST);
        ComplexSymbolFactory csf = new ComplexSymbolFactory();
        Parser parser = new Parser(lexer, csf);
        try {
            Main.Data.ParseOutput = parser.parse().toString();
        } catch (Exception ex) {
            Logger.getLogger(ResultJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
