package GUI;

import CUP.Parser;
import JFlex.LexerScanner;
import JFlex.SymbolTable;
import java.io.BufferedReader;
import java.io.FileReader;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ScannerBuffer;
import java_cup.runtime.XMLElement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohamad Amin Javan
 */
public class ResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionsJPanel
     */
    public ResultJPanel() throws Exception {
        CreateResult();
        CreateTable();
        initComponents();
        TLjTextPane.setText(Main.Data.TLOutput);
        TLjTextPane.setEnabled(false);
        ParsejTextPane.setText(Main.Data.ParseOutput);
        ParsejTextPane.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainFrameTitlejLabel = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        TLjScrollPane = new javax.swing.JScrollPane();
        TLjTextPane = new javax.swing.JTextPane();
        PTjScrollPane = new javax.swing.JScrollPane();
        PTjTable = new javax.swing.JTable();
        ParsejScrollPane = new javax.swing.JScrollPane();
        ParsejTextPane = new javax.swing.JTextPane();
        ReturnjButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        MainFrameTitlejLabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        MainFrameTitlejLabel.setText("Java Compiler Project");
        MainFrameTitlejLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TLjTextPane.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TLjScrollPane.setViewportView(TLjTextPane);

        jTabbedPane.addTab("Tokens List", TLjScrollPane);

        PTjTable.setModel(CreateTable());
        PTjScrollPane.setViewportView(PTjTable);

        jTabbedPane.addTab("Parse Table", PTjScrollPane);

        ParsejScrollPane.setViewportView(ParsejTextPane);

        jTabbedPane.addTab("Parse", ParsejScrollPane);

        ReturnjButton.setText("Return");
        ReturnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(MainFrameTitlejLabel)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnjButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainFrameTitlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturnjButton)
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnjButtonActionPerformed

        Main.Data.MF.setContentPane(Main.Data.MF.cp);
        Main.Data.MF.pack();

    }//GEN-LAST:event_ReturnjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainFrameTitlejLabel;
    private javax.swing.JScrollPane PTjScrollPane;
    private javax.swing.JTable PTjTable;
    private javax.swing.JScrollPane ParsejScrollPane;
    private javax.swing.JTextPane ParsejTextPane;
    private javax.swing.JButton ReturnjButton;
    private javax.swing.JScrollPane TLjScrollPane;
    private javax.swing.JTextPane TLjTextPane;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables

    private void CreateResult() throws Exception {

        LexerScanner LS = new LexerScanner();
        Main.Data.TLOutput = LS.Run(Main.Data.file);
        
        ComplexSymbolFactory csf = new ComplexSymbolFactory();
        SymbolTable ST = new SymbolTable(new BufferedReader(new FileReader(Main.Data.file.getAbsolutePath())), csf);
        ScannerBuffer SB = new ScannerBuffer(ST);
        Parser P = new Parser(SB, csf);
        XMLElement e = (XMLElement) P.parse().value;
        
        Main.Data.PTOutput = Parser.getDebug_parser(P);
        Main.Data.ST = ST;
        
    }
    
    private DefaultTableModel CreateTable(){
        
        String[] COL_HEADER ={"ID Number","Identifier","Type","value"};
        DefaultTableModel tableModel = new DefaultTableModel(COL_HEADER, 0);
        for(int i=0 ; i < Main.Data.IdentifierArr.size() ; i++)
            tableModel.insertRow(i, Main.Data.IdentifierArr.get(i));
        return tableModel;
        
    }
    
}
